version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boilerplate-app
    volumes:
      - ..:/workspace:cached
    networks:
      - sail
      - local-infra-net
    depends_on:
      - mysql
    command: bash -c "cd /workspace && php artisan serve --host=0.0.0.0 --port=8000 & sleep infinity"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.boilerplate.rule=Host(`boilerplate.localhost`)"
      - "traefik.http.services.boilerplate.loadbalancer.server.port=8000"
      - "traefik.docker.network=local-infra-net"

  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: boilerplate-mysql
    ports:
      - '${FORWARD_DB_PORT:-33060}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
      MYSQL_USER: '${DB_USERNAME:-sail}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'boilerplate-mysql-data:/var/lib/mysql'
      - './create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
      - local-infra-net
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD:-secret}'
      retries: 3
      timeout: 5s

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: boilerplate-pma
    environment:
      - PMA_HOST=boilerplate-mysql
      - PMA_USER=sail
      - PMA_PASSWORD=secret
    networks:
      - sail
      - local-infra-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma-boilerplate.rule=Host(`pma.boilerplate.localhost`)"
      - "traefik.http.services.pma-boilerplate.loadbalancer.server.port=80"
      - "traefik.docker.network=local-infra-net"
    depends_on:
      - mysql

networks:
  sail:
    driver: bridge
  local-infra-net:
    external: true

volumes:
  boilerplate-mysql-data:
    driver: local
